select * from customer limit 20

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';

ALTER TABLE customer
RENAME COLUMN "purchase amount (usd)" TO purchase_amount_usd;

ALTER TABLE customer
RENAME COLUMN "discount applied" TO discount_applied;


--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY gender;



--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (
      SELECT AVG(purchase_amount_usd)
      FROM customer
  );


--Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    "item purchased",
    ROUND(AVG("review rating")::numeric, 2) AS "Average Product Rating"
FROM customer
GROUP BY "item purchased"
ORDER BY AVG("review rating") DESC
LIMIT 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select "shipping type",
avg(purchase_amount_usd)
from customer
where "shipping type" in ('Standard','Express')
group by "shipping type"

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

 select "subscription status",
 count("customer id") as total_customers,
 round(avg(purchase_amount_usd),2)as avg_spend,
 round(sum(purchase_amount_usd),2)as total_revenue
 from customer
 group by "subscription status"
 order by total_revenue,avg_spend desc;
 
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select "item purchased",
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by "item purchased"
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT 
        "customer id",
        "previous purchases",
        CASE
            WHEN "previous purchases" = 1 THEN 'New'
            WHEN "previous purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


--08. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        "item purchased",
        COUNT("customer id") AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT("customer id") DESC) AS item_rank
    FROM
        customer
    GROUP BY
        category, "item purchased"
)
SELECT
    item_rank,
    category,
    "item purchased",
    total_orders
FROM
    item_counts
WHERE
    item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select "subscription status",
count("customer id") as repeat_buyers
from customer
where "previous purchases">5
group by "subscription status"

--Q10. What is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc;